add support for global forwarding rule
GoogleCloudPlatform/terraform-validator pull request #185
Opened 2021-02-17 23:01 UTC by ericyz

2021-02-17 23:07 UTC, ericyz commented
Hi @melinath , this PR is ready for review

2021-02-18 22:19 UTC, melinath requested changes

2021-02-18 22:19 UTC, melinath commented on converters/google/mappers.go
>  		"google_storage_bucket":        {{convert: converter.GetStorageBucketCaiObject}},
It looks like this line snuck in here & is causing test compilation to fail.
```suggestion
```

2021-02-22 22:42 UTC, melinath requested changes
Tests are failing - it looks like the underlying issue may be:

```
ERROR: logging before flag.Parse: I0222 07:31:27.689205    7315 convert.go:187] unsupported resource: google_compute_global_forwarding_rule
```

If looks like the `mappers` contains `google_compute_forwarding_rule` instead of  `google_compute_global_forwarding_rule` - should it include `_global_`?

2021-03-02 00:07 UTC, melinath approved these changes
LGTM

2021-03-02 00:08 UTC, merged