add support for pubsub subscription
GoogleCloudPlatform/terraform-validator pull request #186
Opened 2021-02-17 23:05 UTC by ericyz

2021-02-17 23:06 UTC, ericyz commented
Hi @melinath , this PR is ready for review

2021-02-18 22:20 UTC, melinath requested changes

2021-02-18 22:20 UTC, melinath commented on converters/google/mappers.go
>  		"google_storage_bucket":        {{convert: converter.GetStorageBucketCaiObject}},
It looks like these two keys need to be deleted - currently causing test compilation to fail.

2021-02-22 22:37 UTC, melinath requested changes
Test failures:

```
FAIL: TestCLI/v=0.12/tf=example_pubsub_subscription/offline=false/cmd=convert (0.00s)
            cli_test.go:244: unmarshaling: json: cannot unmarshal object into Go value of type []google.Asset
FAIL: TestCLI/v=0.12/tf=example_pubsub_subscription/offline=true/cmd=convert (0.00s)
            cli_test.go:244: unmarshaling: json: cannot unmarshal object into Go value of type []google.Asset
```

I think the `.tfplan.json` and `.json` files might be flipped.

2021-03-01 00:28 UTC, ericyz commented
> Test failures:
> 
> ```
> FAIL: TestCLI/v=0.12/tf=example_pubsub_subscription/offline=false/cmd=convert (0.00s)
>             cli_test.go:244: unmarshaling: json: cannot unmarshal object into Go value of type []google.Asset
> FAIL: TestCLI/v=0.12/tf=example_pubsub_subscription/offline=true/cmd=convert (0.00s)
>             cli_test.go:244: unmarshaling: json: cannot unmarshal object into Go value of type []google.Asset
> ```
> 
> I think the `.tfplan.json` and `.json` files might be flipped in terms of filename vs content.

Thanks! Fixed the those files

2021-03-01 16:10 UTC, melinath approved these changes
lgtm

2021-03-01 16:10 UTC, merged