Add support for google_compute_network and google_compute_subnetwork
GoogleCloudPlatform/terraform-validator pull request #221
Opened 2021-06-02 18:39 UTC by jday29

Adds support for the `google_compute_network` (#20, #211) and `google_compute_subnetwork` (#20) resource types.

Note: The integration tests failed for me when running within the Docker container (`make build-docker`, `make run-docker`, `make test-integration`) because the `Dockerfile` is installing [Terraform `0.12.20`](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/Dockerfile#L6), but one of the tests expects [Terraform `0.12.24`](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/testdata/templates/example_project_update.tfstate#L3). I updated the version in the `Dockerfile` to install `0.12.24` to get around this issue. Not sure if that impacts any other tests/dependencies, or if we should jump to the latest Terraform `0.12.x` version (`0.12.31` as of Jun 6, 2021)?

It seems like `terraform-google-conversion` supports a large number of resources already, so I didn't update that dependency. Assuming we don't have to update it for the ones listed at https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/master/google, and these changes cover everything required for additional resource types, I may add others that I would like to validate against that aren't currently supported.

2021-06-03 16:02 UTC, melinath requested changes
The CI/CD pipeline is running 12.24 so upgrading the docker container to match is great. Since we only use terraform to run tests, we're okay for now with not being on the latest version (unless someone reports an issue.) In any case, that would need to be a separate discussion from adding these resources. :-)

It looks like a bunch of integration tests are failing:

- TestCLI/v=0.12/tf=full_compute_firewall/offline=true/cmd=convert
- TestCLI/v=0.12/tf=full_compute_firewall/offline=false/cmd=convert
- TestCLI/v=0.12/tf=full_sql_database_instance/offline=false/cmd=convert
- TestCLI/v=0.12/tf=example_compute_firewall/offline=false/cmd=convert
- TestCLI/v=0.12/tf=full_sql_database_instance/offline=true/cmd=convert
- TestCLI/v=0.12/tf=example_compute_firewall/offline=true/cmd=convert

At a quick glance, the problem seems to be that those test cases also (have to?) include compute network resources; now that you've added support for those resources, they also need to be added to the expected output.

2021-06-08 18:52 UTC, melinath approved these changes

2021-06-08 18:52 UTC, merged

2021-06-08 18:53 UTC, jday29 commented
> The CI/CD pipeline is running 12.24 so upgrading the docker container to match is great. Since we only use terraform to run tests, we're okay for now with not being on the latest version (unless someone reports an issue.) In any case, that would need to be a separate discussion from adding these resources. :-)
> 
> It looks like a bunch of integration tests are failing:
> 
> * TestCLI/v=0.12/tf=full_compute_firewall/offline=true/cmd=convert
> * TestCLI/v=0.12/tf=full_compute_firewall/offline=false/cmd=convert
> * TestCLI/v=0.12/tf=full_sql_database_instance/offline=false/cmd=convert
> * TestCLI/v=0.12/tf=example_compute_firewall/offline=false/cmd=convert
> * TestCLI/v=0.12/tf=full_sql_database_instance/offline=true/cmd=convert
> * TestCLI/v=0.12/tf=example_compute_firewall/offline=true/cmd=convert
> 
> At a quick glance, the problem seems to be that those test cases also (have to?) include compute network resources; now that you've added support for those resources, they also need to be added to the expected output.

Sorry about that, I forgot to run the integration tests against all cases; I only tested mine before merging.

2021-06-08 18:57 UTC, melinath commented
no worries! Thanks for the update :-)