update ancestry manager to use cfg
GoogleCloudPlatform/terraform-validator pull request #283
Opened 2021-08-04 23:21 UTC by ScottSuarez

fixes https://github.com/GoogleCloudPlatform/terraform-validator/issues/279

credentials/token were not being used for resourceManager initialization.

2021-08-05 23:04 UTC, melinath requested changes
The general approach looks good. I have some small fixes & questions.

2021-08-05 23:04 UTC, melinath commented on ancestrymanager/ancestrymanager_test.go
> -		{name: "owner_project_online", target: amOnline, query: ownerProject, want: ownerAncestryPath},
Are these tests replaced anywhere / would it be possible to replace them?

2021-08-05 23:04 UTC, melinath commented on tfgcv/planned_assets.go
> +		return nil, errors.Wrap(err, "building google configuration")
(Currently errors from GetConfig are effectively ignored.)

2021-08-05 23:07 UTC, ScottSuarez commented on ancestrymanager/ancestrymanager_test.go
> +	cfgOffline, err := cnvconfig.GetConfig(ctx, anotherProject, false)
oof, nice. moved things around too much

2021-08-05 23:08 UTC, ScottSuarez commented on converters/google/convert_test.go
> +		return nil, errors.Wrap(err, "constructing resource manager client")
done done done

2021-08-06 16:03 UTC, melinath approved these changes
LGTM

2021-08-06 16:03 UTC, merged